theme = "term16_dark"

[editor]
line-number = "relative"
mouse = false
scrolloff = 10
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
"$" = "goto_line_end"

# setting yazi as default file browser
C-e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.select]
i = "select_textobject_inner"
a = "select_textobject_around"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
